name: Debug

on:
  push:
    branches: [main]

jobs:
  debug-git:
    runs-on: ubuntu-latest
    steps:
      - name: debug git
        run: git -v

  debug-push-tags:
    runs-on: ubuntu-latest
    steps:
      - name: debug git
        run: git tag test-${{ github.workflow_sha }}
