name: Debug

on:
  push:
    branches: [main]

jobs:
  debug-push-tags:
    runs-on: ubuntu-latest
    steps:
      - name: debug git
        run: git -v

      - name: checkout
        uses: actions/checkout@v3

      - name: debug config
        run: git config -l

      - name: debug tag
        run: git tag test-${{ github.workflow_sha }}

      - name: debug status
        run: git status

      - name: debug push
        run: git push -v --follow-tags
