name: Debug

on:
  push:
    branches: [main]

jobs:
  debug-push-tags:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: debug config
        run: git config -l

      - name: install
        run: yarn

      - name: Set Version (Snapshot)
        run: npx changeset version --snapshot beta

      - name: debug tag
        run: npx changeset tag

      - name: debug status
        run: git status

      - name: debug log
        run: git status

      - name: debug push
        run: git push -v --tags
