on:
  release:
    types: [released]

jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Create changelog from release
        uses: actions/github-script@v7
        env:
          TAG_NAME: ${{github.event.release.tag_name}}
          BODY: ${{github.event.release.body}}
        with:
          script: |
            const { TAG_NAME, BODY } = process.env;

            console.log(TAG_NAME, BODY);

            console.log(`<Update label="${TAG_NAME}">

            ### Improvements

            ${BODY
              .split('\n')
              .filter(line => line.startsWith('-  ') && !line.includes('Updated dependencies'))
              .map(line => line.replace(/^.*:/, '-'))
              .join('\n')
            }

            </Update>`);
