on:
  release:
    types: [released]

jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Create changelog from release
        uses: actions/github-script@v7
        env:
          TAG_NAME: ${{github.event.release.tag_name}}
          BODY: ${{github.event.release.body}}
        with:
          script: |
            const { TAG_NAME, BODY } = process.env;

            console.log(`<Update label="${TAG_NAME.split('@').at(-1)}">

            ### Improvements

            ${BODY
              .split('\n')
              .filter(line => line.trim().length > 0 && !line.startsWith('###') && !line.includes('Updated dependencies'))
              .map(line => line.trim().replace(/^.*:/, '-').replace(/\s+/, ' '))
              .join('\n').replace(/\n([^-])/, '\n- $1')
            }

            </Update>`);
